create table drivers (
    id bigint generated by default as identity primary key,
    name varchar(120) not null,
    license_number varchar(20) not null,
    license_category varchar(5) not null,
    license_expiry date not null,
    phone varchar(30),
    active boolean not null,
    constraint uk_drivers_license_number unique (license_number)
);

create table vehicles (
    id bigint generated by default as identity primary key,
    plate varchar(10) not null,
    brand varchar(60) not null,
    model varchar(80) not null,
    model_year integer not null,
    current_km integer not null,
    status varchar(30) not null,
    driver_id bigint,
    constraint uk_vehicles_plate unique (plate),
    constraint fk_vehicles_driver foreign key (driver_id) references drivers (id),
    constraint chk_vehicles_current_km check (current_km >= 0),
    constraint chk_vehicles_status check (status in ('ACTIVE', 'IN_MAINTENANCE', 'INACTIVE'))
);

create table taxes (
    id bigint generated by default as identity primary key,
    vehicle_id bigint not null,
    type varchar(30) not null,
    description varchar(140) not null,
    due_date date not null,
    amount numeric(12, 2) not null,
    paid boolean not null,
    payment_date date,
    constraint fk_taxes_vehicle foreign key (vehicle_id) references vehicles (id),
    constraint chk_taxes_amount check (amount >= 0),
    constraint chk_taxes_type check (type in ('IPVA', 'LICENSING', 'INSURANCE', 'FINE', 'OTHER'))
);

create table maintenances (
    id bigint generated by default as identity primary key,
    vehicle_id bigint not null,
    type varchar(40) not null,
    description varchar(160) not null,
    performed_at date,
    odometer_at_service integer,
    next_due_date date,
    next_due_km integer,
    cost numeric(12, 2),
    notes varchar(500),
    constraint fk_maintenances_vehicle foreign key (vehicle_id) references vehicles (id),
    constraint chk_maintenances_odometer check (odometer_at_service is null or odometer_at_service >= 0),
    constraint chk_maintenances_next_due_km check (next_due_km is null or next_due_km >= 0),
    constraint chk_maintenances_cost check (cost is null or cost >= 0),
    constraint chk_maintenances_type check (
        type in ('OIL_CHANGE', 'TIRE_ROTATION', 'BRAKES', 'TRANSMISSION', 'FLUIDS', 'ALIGNMENT', 'INSPECTION', 'OTHER')
    )
);

create index idx_vehicles_driver_id on vehicles (driver_id);
create index idx_taxes_vehicle_id on taxes (vehicle_id);
create index idx_taxes_due_date on taxes (due_date);
create index idx_maintenances_vehicle_id on maintenances (vehicle_id);
create index idx_maintenances_next_due_date on maintenances (next_due_date);
